spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.27.97:3308/w?useUnicode=true&characterEncoding=utf-8
#    url: jdbc:mysql://123.57.27.97:3306/w?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: root
#logging:
#  level:
#    root: debug
server:
  port: 7001
